[package]
name = "ping-pong"
version = "0.1.0"
authors = [
    "Martin Hochstrasser <highstreeto@users.noreply.github.com>",
    "Stephan Pernkopf <>"
]
edition = "2018"

[dependencies]
actix = "0.8.3"
futures = "0.1.25"
